### ISSUE TITLE
Bug: Proposal parameters input is longer than the others

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#1011]
### Overview

See screenshot

### Steps to reproduce

n/a

### Screenshots / Video

<img width="695" alt="Screenshot 2023-02-22 at 12 41 19 PM" src="https://user-images.githubusercontent.com/384559/220716434-5729cbe1-c0ac-427a-a37c-ad38a5c59375.png">

### Version

Dev (app.dev.fractalframework.xyz/)

### Browser

Firefox

### Operating System

None

### web3 wallet

None

**Comment by herbig** [comment]
@Da-Colon it seems like this is fixed already?

**Comment by Da-Colon** [comment]
Ha yessir, It has been fixed
