### ISSUE TITLE
Mobile Ready | Favorites + Wallet Menu

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#1016]
We have a few designs still to be implemented for mobile devices:

https://www.figma.com/file/mtgtToPSlKsf3JZ2igEjVF/Use-Existing-Token-and-Mobile-Menu?node-id=5449%3A42444&t=IOj16CuUQB7lhFx6-4

https://www.figma.com/file/mtgtToPSlKsf3JZ2igEjVF/Use-Existing-Token-and-Mobile-Menu?node-id=5472%3A41701&t=IOj16CuUQB7lhFx6-4

**Comment by Da-Colon** [comment]
@xraystyle1980 I guess these designs were never implemented. pretty old. I imagine we can close this.

**Comment by adamgall** [comment]
Let's close it 👍
