### ISSUE TITLE
Mobile | Ready | Wallet Menu

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#1017]
https://www.figma.com/file/mtgtToPSlKsf3JZ2igEjVF/Use-Existing-Token-and-Mobile-Menu?node-id=5472%3A41701&t=IOj16CuUQB7lhFx6-4

**Comment by herbig** [comment]
Merged this into a single ticket with Favorites:

https://github.com/decent-dao/fractal-interface/issues/1016
