### ISSUE TITLE
Bug: DAO hierachy - visual bug 2.0

### ISSUE THREAD

**Issue by tomstuart123** [decent-dao/fractal-interface#1052]
### Overview

This is an issue I only saw arise 1.5 weeks ago. In short, when on the root parentDAO, the DAO hierachy beneath it looks flat regardless of if there are multiple subDAO levels.

****Case Study 1 -**** 

- This is how it should look (this is the view from the subDAO level called 'subDAO CEO')
![Screen Shot 2023-03-06 at 11 15 35 AM](https://user-images.githubusercontent.com/31554133/223095498-4bb07141-09be-4109-abf7-d9a2ca769eb0.png) - https://app.dev.fractalframework.xyz/#/daos/0x0A7b6857DBB2a7Ae3F1618f5f348d0813Ce74d79/nodes

- This is how it actually looks from the parent though called - 'Community Parent example'(i.e. the error) - https://app.dev.fractalframework.xyz/#/daos/0x952C20b4eC7A7000DAa4282Bd293100FE95CF0e0/nodes
![Screen Shot 2023-03-06 at 11 16 09 AM](https://user-images.githubusercontent.com/31554133/223095601-d350d873-3bd0-4a30-b95b-8a35e44fa0be.png)

- Extra note - when loading incorrectly, the subDAO level loads to the page after it's children. Maybe it's a looping issue

Case study 2 - Exactly the same. 
- At the subDAO level it works fine - https://app.dev.fractalframework.xyz/#/daos/0xE5B25d6b5E7639599b39a13A0A5C88Cb07121Bc3/nodes
- At the parent level it doesn't as it looks like a flat structure - https://app.dev.fractalframework.xyz/#/daos/0x3aCda9C9DA5467Af24b8849111DfB6Dc333c447f/nodes

### Steps to reproduce

1. Navigate to the links in overview. 2) Check the DAO hierachy pages when at the rootParent vs. at any subDAO level. 3. Compare the differences

### Screenshots / Video

See Overview

### Version

Dev (app.dev.fractalframework.xyz/)

### Browser

Chrome (or Chromium based)

### Operating System

None

### web3 wallet

None

**Comment by Da-Colon** [comment]
I'm going to mark this issue with a "follow up" for now. and explore https://sim51.github.io/react-sigma/ with @xraystyle1980 for a possible upgrade
