### ISSUE TITLE
Bug: Configure Multisig input bugs

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#1111]
### Overview

While testing @Da-Colon's refactor work, I noticed a number of issues with the Configure Multisig step in DAO creation, that seem unrelated to the refactor...

### Steps to reproduce

~~1. total signers allows any number (but seems to cap how many inputs are actually created). We should limit this field to 2 character length, in order to cap at 99~~
2. clearing total signers doesn't update the signer inputs created. Deleting the field should update the generated inputs to 1 (but leave the field empty), and clicking outside the field should update it to 1 (as it does correctly if you enter 0).
~~3. deleting a signer with the trash icon does not update the Total Signers field, it just clears it. This should update the field to signers - 1.~~
~~4. (minor) Total signers / signature threshold fields could have hint text of `99`~~

### Version

Dev (app.dev.fractalframework.xyz/)

### Browser

All

### Operating System

None

### web3 wallet

None

**Comment by Da-Colon** [comment]
This one has been fixed as well.

**Comment by herbig** [comment]
> This one has been fixed as well.

hmm, yeah it seems mostly fixed

I think we should be able to delete everything from the total signers field though, right now it's impossible to get total signers greater than 19 without knowing to highlight the whole field
