### ISSUE TITLE
Bug: Trash Icon for token allocations keeps incorrect allocation input

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#1113]
### Overview

When deleting a row from the initial token allocations, the address is removed, but the allocation assigned to it is not, resulting in the remaining allocation numbers being incorrect.

### Steps to reproduce

1. Enter two token allocations with address / amount
2. Delete the first token allocation
3. The second allocation now becomes the first (expected) however it now has the allocation from the previous (deleted) row

### Screenshots / Video

<img width="1007" alt="Screenshot 2023-04-05 at 7 07 55 PM" src="https://user-images.githubusercontent.com/384559/230231553-d2f99898-bacf-43d7-b2d2-8b19c1dddf09.png">
<img width="1006" alt="Screenshot 2023-04-05 at 7 08 06 PM" src="https://user-images.githubusercontent.com/384559/230231559-71642cc8-16bc-4125-96ff-ba7d5d2f4084.png">

### Version

Dev (app.dev.fractalframework.xyz/)

### Browser

Firefox

### Operating System

None

### web3 wallet

None

**Comment by Da-Colon** [comment]
I think this one has been fixed

**Comment by herbig** [comment]
> I think this one has been fixed

just tested, this is still an issue

**Comment by herbig** [comment]
actually this looks fixed @Da-Colon, all good!
