### ISSUE TITLE
Able to vote with 0 power

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#1201]
### Overview

1. Create a token voting DAO
2. Without delegating your power, create a proposal (voting options do not appear because you have no power)
3. Delegate to yourself, voting options now appear because _you currently have voting power_
4. Vote on the proposal, which works, but votes appears in history as 0 (this is correct)

Since you've delegated after the proposal was created, you should have 0 voting power on that proposal, however the UI is checking your `current` power to determine if you can vote.

The reverse of this issue is much more problematic, if a proposal is created and then a user transfers all their tokens, the front end will remove the ability to vote on a proposal for which they have power to vote.

### Solution

To determine whether to display the voting options on a proposal details page:

- For ERC20 **We should be checking your historical voting power**, i.e. the Votes snapshot.
- For ERC721 We should be checking their current NFTs _that haven't already been used to vote_

### Version

Dev (app.dev.fractalframework.xyz/)

**Comment by adamgall** [comment]
Reopening this issue because it wasn't actually fixed yet. #1305 was merged with this bug still knowingly not fixed.

**Comment by adamgall** [comment]
I *think* this has finally been fixed, but still need to do some testing to confirm.
