### ISSUE TITLE
Add Snapshot API Key

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#1273]
### Overview

Snapshot is adding request limits to their API, as of September 12.  We will need to add an API key.

### Deadlines
Need shipped/tested by Nov. 2nd

### Additional Info

<img width="475" alt="Screenshot 2023-08-15 at 9 48 30 AM" src="https://github.com/decent-dao/fractal-interface/assets/384559/611c0847-6702-4e42-b729-fb428576bf0a">

### Version

Dev (app.dev.fractalframework.xyz/)

**Comment by herbig** [comment]
submitted a request for an API key from Snapshot, pending a response

**Comment by adamgall** [comment]
Closing this as it's not priority. Not affecting any users.
