### ISSUE TITLE
Hats treasury bug

### ISSUE THREAD

**Issue by sethhrbek** [decent-dao/fractal-interface#1282]
Get details from Tom on the safe address so we can recreate.

1. Determine what the bug is and fix
2. See if we need better failsafes in case some weird data comes in (these should already exist but do a quick audit)

**Comment by Da-Colon** [comment]
Not sure @tomstuart123 ?

**Comment by tomstuart123** [comment]
Parker had this issue when opening a treasury of a friend of his. It was an older version of the product so I'd recommend closing this now
