### ISSUE TITLE
Refactor data flow and performance improvements

### ISSUE THREAD

**Issue by mudrila** [decent-dao/fractal-interface#1296]
The problem was found while working on https://github.com/decent-dao/fractal-interface/issues/1294

## Initial context

The problem is occurring due to the linear dependency between different parts of `FractalNode` object that are fetched in different places. This leads to huge performance impact, as well as non-usable modularity that we have in place (where we have state bits organized in a modular way, but in fact they have direct logical linking across the codebase). This also makes overall performance of the application drastically worse due to a large amount of re-renderings of the components and UI.

## Solution

In simple words - we need to refactor our data flow. There're 2 possible ways of doing so:

- Refactor application to use SSR, and thus either use state management library that will preserve state for the client (or keep using context ) while passing data from the server. We could leverage all sorts of Next.js API for granular data fetching
- Or keep using client-only rendering, but make the dependency between data more straightforward and bound, also ensuring that all the data fetched during same rendering cycle.

Any of the proposed solutions will be quite a shift, and for me personally it feels like using SSR will give more benefits for the end-user (at the same time - in some term sacrificing the privacy, as there will be more Server part, which doesn't store the data, but still)

Also, SSR would be more complicated to implement at first due to the need of upgrading to the latest Next.js and Chakra (our current Chakra + Next.js versions ain't working with SSR 😢 ), but I think it will be simpler to support further on.

**Comment by adamgall** [comment]
@mudrila I agree that it's time to review and refactor data flow in the `fractal-app`.

There's a lot to consider here.

My first thought is that your second solution is somewhat of a subset of the first solution. Meaning: regardless of which solution is implemented, it will require reviewing and refactoring data structures and data fetching flows. However, in the first solution, we would need to that work while _also_ taking into consideration the evolving infrastructure of _where_ data is fetched and html is rendered.

But, I'm making a good number of assumptions here.

It would be nice to see a visual state diagram or flow chart or something like that, which shows the different states that data might be in, and how to get from one state to another, and how data is fetched throughout that process. Maybe it would even be best to do that from scratch, ignoring how the app is currently implemented. Once we've got our heads wrapped around how we _want_ state and data in app to behave, that might give us more information to make a decision on how we want to start refactoring.

Thoughts?

**Comment by adamgall** [comment]
Closing this because efforts are ongoing to fix these things.
