### ISSUE TITLE
Sepolia support

### ISSUE THREAD

**Issue by mudrila** [decent-dao/fractal-interface#1316]
To implement Sepolia support we need following changes:

- [x] Deploy smart contracts, verify them on Etherscan
- [x] Publish updated `fractal-contracts` package to NPM
- [x] Create Subgraph hub at Sepolia testnet
- [x] Use updated `fractal-contracts` NPM package within `fractal-interface` codebase
- [x] Add configuration for Sepolia network support for Safe API, Wallet connection

**Comment by adamgall** [comment]
This is complete
