### ISSUE TITLE
WalletConnect modal is using an outdated and non-functional version

### ISSUE THREAD

**Issue by jaybuidl** [decent-dao/fractal-interface#1327]
### Overview

WalletConnect doesn't connect because v1 has been retired [since July 2023](https://medium.com/walletconnect/weve-reset-the-clock-on-the-walletconnect-v1-0-shutdown-now-scheduled-for-june-28-2023-ead2d953b595). 

This frontend is using v1.8, current version is [v2.11](https://www.npmjs.com/package/@walletconnect/ethereum-provider?activeTab=versions).

### Version

Dev (app.dev.fractalframework.xyz/)

**Comment by adamgall** [comment]
Thanks for opening this issue!

After recent updates to the app, WalletConnect is working again.
