### ISSUE TITLE
Disconnecting Wallet Causes App to Crash

### ISSUE THREAD

**Issue by adamgall** [decent-dao/fractal-interface#1369]
![Image](https://github.com/decent-dao/fractal-interface/assets/38386583/9fd5fe90-f16c-4a0e-bd35-c3b60cd4d75a)

This error shows after disconnecting the wallet in a loop. This freezes the app unitl it eventually crashes. This is the same error I see when WalletConnect breaks the app.

This seems to be present on Prod and Dev

**Comment by adamgall** [comment]
@Da-Colon is this issue still present after the RainbowKit -> Web3Modal updates?

**Comment by Da-Colon** [comment]
@adamgall I believe this issue is safe to close now. I don't have any problems now on dev due to recent updates.

**Comment by adamgall** [comment]
You heard the man
