### ISSUE TITLE
Create Proposal - Preview functionality

### ISSUE THREAD

**Issue by tomstuart123** [decent-dao/fractal-interface#1398]
Note: High chance this Issue will be satisfied after the completion of #1363.

---

Feedback from Shutter on making the preview functionality for proposal creation clearer.

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/1ee775eb-b1df-4403-9b1f-c373d11fc728)

Right now we don't utilise a proposal preview functionality. As you can see, you input the details to create a proposal and then instantly get asked to sign

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/21c39864-0494-4819-ac60-4a59ee61b6e1)

However as you can see, in proposal templates we already have a preview functionality that we can share to shutter and confirm if that ticks the boxes they expected.

If so, we can integrate it into proposal creation

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/25a52417-aac5-46a1-9ee2-28768a4a9847)

**Comment by adamgall** [comment]
Does this issue get satisfied when we switch the Proposal flow to the Proposal Template flow??

**Comment by adamgall** [comment]
Closing this because it will be satisfied after completion of #1363
