### ISSUE TITLE
Create Proposal - Larger Text fields

### ISSUE THREAD

**Issue by tomstuart123** [decent-dao/fractal-interface#1400]
See shutter dao member feedback here 

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/f2cde35d-85dd-4ba4-a062-086bfb42589d)

As you can see here our text fields are a good size for addresses (e.g. EOAs, multisigs etc)

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/e579ae44-c435-45ba-bc66-c8c15d57377e)

However for smart contract transactions they require side scroll

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/e60f5606-1731-4f2d-874c-dcd9b3664dd1)

**Comment by adamgall** [comment]
This issue will be satisfied (at least, much less of an issue) after the completion of #1363. The main problem right now is that _all_ parameters for a function call need to be stuffed into one single-line input. After #1363, _each parameter_ will receive its own single-line input, which is totally acceptable IMO.

Closing.
