### ISSUE TITLE
Create Proposal - Immediate error message for 'invalid arguments'

### ISSUE THREAD

**Issue by tomstuart123** [decent-dao/fractal-interface#1401]
Request from shutter member:

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/844823d6-f548-4ce5-8c39-dd67e9351b42)

Assume this relates to the fact that if you provide a function signature or parameter without the other aspect an error appears.

E.g. here

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/68614a61-ec75-41ae-a6d0-8b4c81fb1f8d)

and here

![Image](https://github.com/decent-dao/fractal-interface/assets/31554133/7dafd757-b8d6-4bc5-a689-100870e6758b)

I like the clarity of errors here personally so maybe we consider if the pros of clarity outweigh the cons

**Comment by adamgall** [comment]
This issue will be moot after the completion of #1363, so closing.
