### ISSUE TITLE
Static Upgrade

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#1422]
#### Description:

In light of recent discussions and recurring issues attributed to Server-Side Rendering (SSR) complexities and our current infrastructure setup, I've come to realize that a significant refactor might be beneficial, potentially without the need to entirely remove NextJS from our stack.

**Issue Overview:**

Our current usage of NextJS and its handling of SSR has introduced challenges, particularly in how it distinguishes between Server Components and Client Components based on the component's data. The decision-making process behind the mounting of these components is opaque, leading to unnecessary re-renders as NextJS mounts components and processes the data.

**Proposed Solution:**

I suggest we transition from the current AppRouter setup to a Page Router setup. This approach aims to simplify the process of exporting a static site by minimizing NextJS's inference over our component system. It should provide a more straightforward and controlled environment for managing component rendering and data handling on the client and server sides.

**Considerations:**

- We need to carefully review and potentially adjust the `loadKey` configurations and the conditional logic within `useEffect` hooks. These have been previously implemented to address re-render issues but may not align with the new architecture's logic and performance optimizations.
- This refactor requires thorough testing to ensure that moving to a Page Router setup does not introduce new issues or negatively impact the user experience.
- This may require an update to Netlify's Configurations

**Comment by Da-Colon** [comment]
Update: 

@tomstuart123 @adamgall @mudrila 

## The Past

So there are two PRs attached to this issue. 

In the first PR #1421 , I approached this with the attempt to make NEXTJS static. To this goal I move away from the App Router setup to the Page Router setup. This change removes alot of the inferring that NextJS as its expected a SSR setup. This change ultimately resulted in a statically built app which we can see in the build logs in console.

This works. The deployed app in the preview of that PR is running as mostly a statically built site. There is still a 'server' being built and when running dev environment locally some errors pop up on every load as NextJSi continues to use SSR for local dev and it hydrates weirdly in the setup.

## The Present
So we get to PR #1431 , This Development experience would not be great, so I took the plunge to remove NextJS in its entirely and replace the build framework to vite. The details of the changes are in the PR. It really wasn't too bad and I don't expect any new issues to arise. 

I manually created a deploy on the branch since the env changed @adamgall I just used my keys for now since its temporary) to test the deployed site.

**Comment by adamgall** [comment]
Freakin Epic, @Da-Colon

**Comment by adamgall** [comment]
Increasing the "end date" on this issue, to account for the fact that the scope of this Issue (and associated PRs) has increased since it was started. 

This issue is now, as @Da-Colon stated in his previous message, encompassing the removal of NextJS from this codebase.
