### ISSUE TITLE
Swap out mono font for sans-serif font

### ISSUE THREAD

**Issue by xraystyle1980** [decent-dao/fractal-interface#1423]
Requesting to swap out all instances of IBM Plex Mono for IBM Plex Sans. 

As we move forward with cleaning up the UX and UI, we'd like to simplify the font stack by removing the use of IBM Plex Mono and doing a 1:1 swap for IBM Plex Sans. 

IBM Plex Sans is the sans-serif font currently in use so we won't need to add it. 

*Caveat: can we keep the mono font for JUST the code snippets? For instance, on proposal details in the "View executable code" sections.

**Comment by adamgall** [comment]
Closing this due to bigger UI redesigns anyway.
