### ISSUE TITLE
Eliminate the yellow radial gradient background from existence

### ISSUE THREAD

**Issue by xraystyle1980** [decent-dao/fractal-interface#1424]
Please update the background of the app by removing the yellow radial gradient BG and changing the subtle gradient background to a solid color #262521 (which is chocolate 700 currently)

![image](https://github.com/decent-dao/fractal-interface/assets/18615633/53181dd6-7d31-4fb8-8d86-2cb377319728)

**Comment by nicolaus-sherrill** [comment]
This issue title is very metal.
