### ISSUE TITLE
Show DAO address in UX

### ISSUE THREAD

**Issue by sethhrbek** [decent-dao/fractal-interface#198]
After creating a DAO, I had to copy the DAO address from the URL in order to find my way back to it.

We should display the DAO address somewhere prominent on the DAO page(s). 

It could potentially be truncated, but clicking it will copy the full address.

**Comment by dannydecent** [comment]
Quick solution as we work through a more robust UI/UX:

Toast message - Remember to Bookmark this URL to Revisit your Fractal Anytime.

Place the address in the breadcrumb

**Comment by adamgall** [comment]
@dannydecent is your above comment a directive?

**Comment by dannydecent** [comment]
Yes. Still working through the UI needs for this sprint and screens for easy reference.

**Comment by dannydecent** [comment]
![image](https://user-images.githubusercontent.com/100443989/169154702-3850a277-280f-4290-8fd8-397163ae6647.png)

**Comment by adamgall** [comment]
Completing this issue will also complete #268, since we'll be implementing the first instance of a Tooltip UI here.

**Comment by dannydecent** [comment]
@Da-Colon screens updated. assigning you. place in done when its ready to ship.
