### ISSUE TITLE
Proposal Form Validation triggering early

### ISSUE THREAD

**Issue by sethhrbek** [decent-dao/fractal-interface#199]
When filling out the proposal form, as soon as I begin typing in the "Function Signature" input, I get validation errors.

This is a little jarring since I was still in process of filling the form out.

Not sure the best way to handle this, as assume all fields need to be filled until validation can occur -- and the validation may include all 3 fields. Perhaps a single validation message at the bottom (or top) of the proposal which is always present --- starts as "incomplete" and turns to green "complete" once all fields are filled out correctly.

![image](https://user-images.githubusercontent.com/43755993/166980422-ef40ab69-561a-480c-9d9d-347ea782616f.png)

**Comment by Da-Colon** [comment]
we could definitely re think the structure of error handling here. currently error handling for this component is handled `onChange`. We could update this error check to happen in a `onSubmit` with the `Create Proposal` only being disabled if there isn't a value in `functionName` and `targetAddress` and if there is an error in `targetAddress`. Once Create Proposal is clicked, we can then do an error check on these fields. 

we could also just move all the error handling to happen after the form is submitted for a cleaner experience during (including `targetAddress`?

The other side of it. is the dev in me likes the instance feedback. We could spend some time to better define how these errors are thrown. and not throw it on all the fields. 

ex: if `(functionSignature.spilt(',').length !== parameters.spilt(',').length) throw error` on `Parameters`. Then once you submit is when the Interface check happens (current way that finds errors).

**Comment by Da-Colon** [comment]
No longer applies / Fixed
