### ISSUE TITLE
Event handlers. Data collection etc.

### ISSUE THREAD

**Issue by dannydecent** [decent-dao/fractal-interface#201]
Future feature.

Collecting bounce rates, failed wallet connections etc.

**Comment by dannydecent** [comment]
Future feature. 

Collecting bounce rates, failed wallet connections etc.

**Comment by adamgall** [comment]
examples: Sentry, Datadog

**Comment by dannydecent** [comment]
please review - https://mode.com/

**Comment by Da-Colon** [comment]
@adamgall I know we spoke a little about this a while back. should this issue be closed for now?

I also came across [pendo](https://pendo.io) which shapeshift uses

**Comment by adamgall** [comment]
we can close this for now
