### ISSUE TITLE
Tooltip UI

### ISSUE THREAD

**Issue by adamgall** [decent-dao/fractal-interface#268]
We're looking for a reusable pattern for sticking tooltip popups wherever we want them

**Comment by dannydecent** [comment]
![DAO Dashboard](https://user-images.githubusercontent.com/100443989/169582906-387c9781-7efb-4063-b7de-e6f1551a92ca.png)


Only using one tool tip at this time. Showing DAO address when hovering/tapping on the DAO name in the main screen/dashboard.
