### ISSUE TITLE
Update drop down items and links

### ISSUE THREAD

**Issue by dannydecent** [decent-dao/fractal-interface#284]
Current copy => "Updated Copy" | Link: url

Contact => "Community" | Link: https://discord.com/invite/24HFVzYVRF (same)
Support => "Overview" | Link: https://docs.fractalframework.xyz/welcome-to-fractal/overview/what-is-fractal
FAQ => "FAQ" | Link: https://docs.fractalframework.xyz/welcome-to-fractal/overview/faq
Add: "Documents" => Link: https://docs.fractalframework.xyz/welcome-to-fractal/

**Comment by adamgall** [comment]
"Documents" lol

**Comment by adamgall** [comment]
@dannydecent which icon should i use for the new `docs` item?

i'm looking here, nothing is really popping out to me:
https://app.zeplin.io/project/621555dace85c3173da9f601/styleguide/components?seid=625eaecf75ae1910e6ccb9a3

**Comment by dannydecent** [comment]
https://zpl.io/qy8B9BN
