### ISSUE TITLE
Delegate explainer tooltip

### ISSUE THREAD

**Issue by dannydecent** [decent-dao/fractal-interface#286]
use a tool tip or alert on the bottom

Copy: Enter the address to delegate your vote to. Click "Self" to assign yourself.

**Comment by adamgall** [comment]
On the Treasury component, there's a similar info message being used below the main component.

![Screen Shot 2022-05-27 at 8 43 41 AM](https://user-images.githubusercontent.com/706929/170701505-2a9206be-ac51-4d61-9755-726876560deb.png)

**Comment by dannydecent** [comment]
Yes, lets use this same patter, this is the alert pattern I was referencing. 

Nice to have, only if its already coded up; this info message/alert will go away after the first action/instance has been taken.

**Comment by adamgall** [comment]
Closed as of #301
