### ISSUE TITLE
Allow User to choose proposal length on DAO deploy

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#307]
### Discussed in https://github.com/decent-dao/fractal-interface/discussions/244

<div type='discussions-op-text'>

<sup>Originally posted by **Da-Colon** May  6, 2022</sup>
Opening an discussion on the lift it would take to allow a user to choose proposal length on DAO creation</div>

## Conversation Conclusion
![image](https://user-images.githubusercontent.com/38386583/172438324-54ab939e-2d15-4d1c-a43f-8c29485b723d.png)

## Requirements
- @xraystyle1980 Need Designs for choose a length of time:
  - 3 options for quick select (1 day, 3 days, 1 week) 
  - input for entering number of hours
- open Product question:
  - @dannydecent does the above options for a user make sense?

**Comment by adamgall** [comment]
No progress is being made here, going to push this back into the backlog

**Comment by dannydecent** [comment]
@xraystyle1980 bump - need to discuss together
