### ISSUE TITLE
Support Native Tokens via naming conventions

### ISSUE THREAD

**Issue by christopherdancy** [decent-dao/fractal-interface#359]
Future proof the app - to be chain agnostic.

Success Criteria 
- Solidity Treasury Module - should be native token agnostic
- UseTreasuryAssets.ts - should be native token agnostic
- useTreasuryEvents.ts - shoujld also be native token agnositc

**Comment by christopherdancy** [comment]
As long as the native asset is EVM w/ ethers precision - then it will not create any functional changes. 

The solidity changes would require some naming changes and a redeployment of contracts. However, I am not sure this is needed atm.

**Comment by Da-Colon** [comment]
I think this is safe to close
