### ISSUE TITLE
Delete Favorite

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#370]
Should have a way to remove from favorites (delete from local storage)

**Comment by adamgall** [comment]
This should be implemented already... click the same star that you clicked to mark a DAO as "favorite" to un-mark it as "favorite".

But maybe you're talking about putting that "un-favorite" logic on the dedicated "favorites" page as well, which I'm not opposed to.

**Comment by Da-Colon** [comment]
You are correct siir

**Comment by Da-Colon** [comment]
no longer applies
