### ISSUE TITLE
SubDAO Treasury Allocation (UI)

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#377]
There should be an additional step when create a subDAO. User should be able to 'fund' a subDAO with assets from treasury DAO

Requirements/Context:
[UI]
- Screen should appear after `TokenAllocation` Step.
- Screen should show native and erc20 tokens available from the treasury
- Screen should show erc721 tokens available from treasury
- Screen should have an input for manually entering amounts on native and erc20 tokens
- Screen should have an 'MAX' button for easily entering the max amount of available tokens
- Treasury Data should be display

[Data]
Three new items need to be added to the DAOcreator:

TokenFunded[]
NFTFunded[]
treasuryContractAddress

 ```tsx
type TokenFunded = {
  address: string,
  amount: string
}

type NFTFunded = {
  address: string,
  token_id: string
}
```

**Comment by adamgall** [comment]
@Da-Colon i love seeing this. thank you for documenting out the requirements for the work you're doing
