### ISSUE TITLE
Proposal created without Voting powers fail

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#387]
Proposal's created this way end up failing while queuing

**Comment by adamgall** [comment]
what does this mean? what should the fix look like?

**Comment by Da-Colon** [comment]
O yeah good call. This happens when I create a new DAO, do the token allocation to myself. But before 'Delegating' voting rights and I try to create a Proposal. The proposal will be created but will fail when attempting to `Queue Proposal`.  I don't have all the context on how queuing works to say that the solution here is.

**Comment by adamgall** [comment]
I wonder if it's easy to check the "total delegated votes" for a given token? If so, we could disable the "create proposal" button if that number is 0.

@christopherdancy thoughts on this approach?
