### ISSUE TITLE
Treasury Claiming - SubDAO Allocation

### ISSUE THREAD

**Issue by christopherdancy** [decent-dao/fractal-interface#392]
If a treasury is allocated x amount of parent tokens - then the treasury has the right to claim x amount of child tokens. As it is now - anyone can claim on behalf of the treasury. Therefore - there will be x amount of tokens which get transferred to the treasury.

Here is the problem - how is this displayed on the front-end - how should this be deposited so it shows up on the frontend.

**Comment by Da-Colon** [comment]
@christopherdancy @tbwebb22 @adamgall I believe this was talked more about recently in discord. My question here is something that needs to be figured out done sooner or later?

**Comment by adamgall** [comment]
I'm not quite sure exactly the issue being described here.

> If a treasury is allocated x amount of parent tokens - then the treasury has the right to claim x amount of child tokens.

I don't follow this premise. @christopherdancy are you saying that during a subDAO creation, if a child DAO is being allocated with some amount of the parent DAO's tokens, then the parent DAO has a right to claim some of the child DAO's tokens? Why is that the case?

The case in which a parent DAO has a right to claim some child DAO tokens, IMO, occurs _not_ when the parent DAO is sending it's own tokens to the child DAO, but when the child DAO is allocating some percentage of it's own tokens to existing parent DAO token holders.

**Comment by christopherdancy** [comment]
@adamgall Correct - During the funding of child DAO, there is no need to worry about claim rights. However, when we speak about a Parent treasury which owns Parent tokens at the time the snapshot is captured has to worry about claim rights.

To clarify - the parent's treasury may still claim the tokens - however, the frontend will not know which tokens have been sent to the treasury unless the deposit event is emitted.

**Comment by adamgall** [comment]
> To clarify - the parent's treasury may still claim the tokens - however, the frontend will not know which tokens have been sent to the treasury unless the deposit event is emitted.

Ah yes, this seems to be the crux of what you're getting at, is it not?

@christopherdancy  what does the token flow look like as tokens are minted, allocated to parent token holders, and claimed? What I'm trying to get at is, how can we make it so that those tokens are _eventually_ deposited to the treasury via the treasury's deposit functions.

**Comment by christopherdancy** [comment]
@adamgall yes ser it is!

The current flow is as follows - SubDAO created w/ pToken Allocation - If the treasury owns pTokens at the time of creation, the treasury will have a claim to x cTokens - Anyone may claim on the behalf of the treasury, however, x Tokens will not be deposited via the deposit method. 

A couple solutions are as follows - allow a user to call an arb tx. via the treasury contract or modify the claim contract to call an arb tx. Either way - we will need to think through the possible side affects. I will review this tomorrow and think through other possible solutions.

**Comment by christopherdancy** [comment]
Yes - the new contracts do not address this in any way

**Comment by christopherdancy** [comment]
Well as I remember - we are souring token events based on transfer events and this provided by the gnosis api... no need to even worry about this any longer.

**Comment by herbig** [comment]
cool cool, I'll close this one out then
