### ISSUE TITLE
BUG- Token Allocation

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#414]
![Image](https://user-images.githubusercontent.com/38386583/183113179-07c29903-62e4-449e-a209-788613b36a7c.png)

**Comment by adamgall** [comment]
What's the bug here?

**Comment by Da-Colon** [comment]
In Fractal VC if you want to jump in was about to talk to @christopherdancy about it. @adamgall

**Comment by Da-Colon** [comment]
if you set a 
Supply: 10. 
Parent Allocation: 5
Token Allocations: one addresss -> 5

go to the next screen and submit. notion will happen if you go back to the token allocation screen you will see added allocations and an supply error.

**Comment by Da-Colon** [comment]
I think I know whats happening here. so the 'rest' that gets sent to the new SubDAO's treasury isn't accounting for the parent token allocation @adamgall
