### ISSUE TITLE
Input | Usability - Validation not applied to pasted data

### ISSUE THREAD

**Issue by SudoPumpkin** [decent-dao/fractal-interface#442]
Branch(es): App, Dev

**Observation**
Form validation does not always apply to pasted input.

_Examples_
- Pasted in numbers with decimals are accepted into the numerical input fields.
- More then 5 characters are allowed to be pasted into the Token Symbol field.

**Expected Behavior**
- Pasted in numbers are converted to whole numbers or not accepted(error message)
- More then 5 characters pasted into the Token Symbol field are met with an error message.

_STR_
1. Log on to https://app.dev.fractalframework.xyz/#/daos/new
2. Input a Fractal Name('Bob's Burgers')
3. Click 'Next'
4. Select the default radio button selection of '1:1 Token Voting'
5. Click 'Next'
6. In a text document type in '0.1'(MS word)
7. Copy the '0.1'
8. Paste this selection into the 'Token Supply' field
9. Notice how this is allowed

All numerical input fields allow this float number pasting.
Also note numerical fields allow the letter 'E' pasted as input but will not allow the user to select the 'Next' button.

![image](https://user-images.githubusercontent.com/86701852/186016071-d2fbf6c5-321e-463d-b44b-3973d0a343f9.png)

**Comment by Da-Colon** [comment]
awesome, this looks great! I'm gonna assign it with a 'good first issue' and 'bug' labels.

**Comment by Da-Colon** [comment]
going to close for now, but we will need to do a stress test on workflows at some point in near future
