### ISSUE TITLE
Functionality | Input - Token Supply and Allocation Amount math

### ISSUE THREAD

**Issue by SudoPumpkin** [decent-dao/fractal-interface#450]
If the user selects the token governance selection of '1:1 Token Voting' and inputs a number greater then '1' into the 'Token Supply' field(i.e. '300') when deployed it will fail. 

_STR_
1. Log on to https://app.dev.fractalframework.xyz/#/daos/new
2. Open your Dev Tools console
3. Input a Fractal Name
4. Click 'Next'
5. Select the default Governance token of '1:1 Token Voting'
6. Click 'Next'
7. In the 'Token Supply' field input '300'
8. In the 'Amount' field input '1'
9. Fill out the remaining fields on this page
10. Click 'Next'
11. Click 'Deploy'
12. Notice error

![image](https://user-images.githubusercontent.com/86701852/186250953-7616e887-d82e-4ff4-9ae6-36e6e36e1b08.png)

https://user-images.githubusercontent.com/86701852/186250973-7fc29e91-1bc7-4fad-bcff-6efaf31d14c3.mp4

**Comment by adamgall** [comment]
@SudoPumpkin nice find.

This seems like a very high priority bug to fix.

@Da-Colon @mudrila @christopherdancy I want to override our current work and understand/fix what went wrong here.

**Comment by Da-Colon** [comment]
Yessir I plan to look into this tonight.

**Comment by adamgall** [comment]
magic
