### ISSUE TITLE
Add Sentry support for all non-prod builds

### ISSUE THREAD

**Issue by adamgall** [decent-dao/fractal-interface#458]
We should add Sentry support to the frontend, but only enable it on non-prod builds.

All engineering contributors of Fractal have been added to the new Sentry team, so anyone should be able to pick this issue up.

https://sentry.io/organizations/decent-1k/projects/fractal-interface/?project=6688050

**Comment by Da-Colon** [comment]
Is this based on github account or decent email?

**Comment by adamgall** [comment]
@Da-Colon decentlabs.io email address. i've just re-invited you.
