### ISSUE TITLE
Subsidary Funding

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#459]
Getting a similar issue when trying to fund a subDAO from a parent DAO treasury 1:1 Token Voting Governance root a 1:1 Token Voting Governance subDAO. 

Repl:
- In a 1:1 Token Voting Governance Parent DAO. 
- Send funds to Treasury (0.05ETH)
- Click Create a subDAO
- Add ETH
- Set to 0.05
- Set other configurations (new subDAO token as normal
- Click Deploy......you will get an error

**Comment by christopherdancy** [comment]
This error appears to occur before the actual proposal is created.
