### ISSUE TITLE
Clicking on ETH on treasury page takes the user to the token address zero

### ISSUE THREAD

**Issue by christopherdancy** [decent-dao/fractal-interface#471]
I am thinking this should go to the users account on etherscan.

steps to reproduce
1. create a dao
2. fund the dao w/ eth
3. view the treasury
4. click on the eth symbol
![Screenshot 2022-08-31 at 11 22 04](https://user-images.githubusercontent.com/69045872/187716415-8d332af9-58e7-454c-b45e-5d482de7b34a.png)

**Comment by adamgall** [comment]
Why the user's address on etherscan? I don't see how that's related to the treasury's ETH balance.

**Comment by adamgall** [comment]
Honestly, I think there's a better more holistic solution for the "links to etherscan" on the treasury page.

Links to the base token (ETH) should go directly to the treasury contract's address on etherscan
Links to the ERC20 token should go to the treasury's balance on the token (`https://etherscan.io/token/<tokenAddress>?a=<treasuryAddress>)

**Comment by Da-Colon** [comment]
no longer epplies
