### ISSUE TITLE
Reenable subsidary funding for Parent DAO -> Child DAO

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#480]
## Issue
Reliant on #479 to be completed first. Temporarily this feature will be skipped in the Gnosis subDAO creations

## requirements for success
- 1:1 Token Voting Governance can fund a Gnosis subDAO
- Gnosis Safe can fund a 1:1 Governance subDAO

**Comment by herbig** [comment]
We've decided to hold off on subsidiary funding for both Usul/Safe for v1, so we'll need to revisit that stage after release.

**Comment by herbig** [comment]
@Da-Colon we have this captured in the roadmap, so I'd like to close this and when we bring it back have a more fully fleshed out product doc / design / then breakdown into issue tickets.
