### ISSUE TITLE
UX Token Allocations don't meet qurom

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#481]
Issue:
When a user creates a 1:1 Token Governance DAO, they are able to create a DAO with not enough tokens allocated to reach default Quorum.

Proposed Solution:
- [ ]  Switch the order of the form screens with the Governance Configuration happens before the Token Allocations
- [ ] Add a check to compare tokenSupply/tokenAllocationsSum with Quorum to check if the user has allocated enough tokens. if not show the user an error and disable deploy.

**Comment by Da-Colon** [comment]
I'd like to follow up with the USUL setup with this. Don't want user to be able to create bricked DAOs from our UI

**Comment by ef3n9r98** [comment]
Hi @Da-Colon, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by sethhrbek** [comment]
@ef3n9r98 -- there is not a budget for this issue (or other issues) right now. If we open up any issues for bounties, we will let you know. Thanks!

**Comment by herbig** [comment]
@Da-Colon this also is captured in the roadmap, via the DAO creation flow redesign.

I'm going to close this, and when we get to a redesign on DAO creation with @xraystyle1980 's help, ordering the steps differently will be part of the discussion.

**Comment by herbig** [comment]
And we'll break DAO redesign into tickets at that point.
