### ISSUE TITLE
Token Name and Symbol

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#490]
Currently there is nothing blocking creating a governance token from being created without a name and symbol. 

## Issue Resolve requirements
- Is this behavior expected?
- if it is expected. currently the Delegation page won't load correctly. The voting weight and power fields will stay in a 'loading' state while the symbol is undefined.

**Comment by adamgall** [comment]
@herbig did #501 handle this issue?

**Comment by herbig** [comment]
> @herbig did #501 handle this issue?

Ah yeah this is fixed now.
