### ISSUE TITLE
Delete the logic that translates select non-mainnet token address into mainnet addresses

### ISSUE THREAD

**Issue by adamgall** [decent-dao/fractal-interface#493]
1. First, gate this code into a conditional that only triggers if the user is NOT connected to mainnet.
2. In a follow up PR, we can delete this code entirely.

_Originally posted by @adamgall in https://github.com/decent-dao/fractal-interface/pull/492#discussion_r969794503_

**Comment by Da-Colon** [comment]
no longer applies
