### ISSUE TITLE
CoinGecko attribution required in fiat display

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#500]
We're using CoinGecko's free API, which requires attribution:

https://www.coingecko.com/en/api/pricing

Design should come up with a simple attribution.

cc: @xraystyle1980 @adamgall 

Related to https://github.com/decent-dao/fractal-interface/pull/492#discussion_r971249895

**Comment by xraystyle1980** [comment]
Added here:
https://www.figma.com/file/gjLSqgm6o1D25yPXiIeqYm/%F0%9F%8E%A8-Fractal-Band-Aids-%7C-Updates-to-live-app-%7C-Q3---Q4-2022?node-id=1510%3A9714

@herbig whether or not we use the Netlify badge, styles are available in the linked Figma file. The font style should already be present in the app however the text color may not be. The color used is coming from a newer library. We can substitute a medium-gray for now if we need to.

**Comment by herbig** [comment]
@brianfryer I think it's cool to keep this separate from the current PR #492 , we'll follow up that with a CoinGecko / Netlify attribution from whoever has bandwidth

**Comment by adamgall** [comment]
Fixed as of #492
