### ISSUE TITLE
Make webapp better equipped for localization

### ISSUE THREAD

**Issue by adamgall** [decent-dao/fractal-interface#52]
There are user-facing English strings strewn throughout the webapp. Proper localization should be implemented.

**Comment by herbig** [comment]
@Da-Colon @adamgall @mudrila I was going to take a look at setting us up for proper localization.  Do either of you have any React localization / internationalization libraries you would suggest?

**Comment by adamgall** [comment]
@herbig I can't remember what library I used the last time I did this, but searching for popular libraries right now yields:

* https://github.com/formatjs/formatjs
* https://github.com/i18next/react-i18next

**Comment by herbig** [comment]
Closing this, we're now properly equipped for localization, but now need to actually get localized strings
