### ISSUE TITLE
Activity Feed implementation follow-up

### ISSUE THREAD

**Issue by mudrila** [decent-dao/fractal-interface#520]
- [ ] Refactor Proposal listing components
- [ ] Implement ERC20 tokens metadata storage in order to show token name/symbol in transactions listing
- [ ] Enhance `ProposalCard` - cover all the texts for buttons when proposal in composed "active" state

**Comment by herbig** [comment]
@mudrila this is in In Progress in our board, should we move this back to TODO for now?

**Comment by Da-Colon** [comment]
no longer applies
