### ISSUE TITLE
BUG: App freezes if transaction is rejected

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#537]
## Description
If connect your wallet and go to deploy a MVD Gnosis safe and reject the transaction in the metamask popup confirmation. the app freezes and becomes unresponsive.

**Comment by herbig** [comment]
On Firefox this does not occur at all.

On Chrome I see about an 8 second freeze, then the app becomes responsive again.

**Comment by SudoPumpkin** [comment]
There is a bit of clunky/laggy behavior in Chrome with canceling a transaction request using MetaMask. I did get app.dev to sort of freeze when canceling then ignore the cancel and complete the transaction. I am trying to reproduce that issue manually. 

![image](https://user-images.githubusercontent.com/86701852/195166352-10e7682b-7c97-4379-ab36-09f8a13ea11c.png)

**Comment by SudoPumpkin** [comment]
Here's the error in the screenshot that the toaster message tells the user to seek out. Perhaps this is related to the clunky behavior?

`Error: user rejected transaction (action="sendTransaction", transaction={"data":"0x126e66e60000000000000000000000001d34c9fac51055098020d2921498028a81fa91de00000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000088000000000000000000000000000000000000000000000000000000000000008c00000000000000000000000000000000000000000000000000000000000000aa00000000000000000000000000000000000000000000000000000000000000b200000000000000000000000000000000000000000000000000000000000000ba0000000000000000000000000d25efe3a1566ea3e899e63c12cca717fb0dad282000000000000000000000000acd04dbc1c452c5aab668ab60deef36c6435d7eb97bf5577c31f56569f3e57ed4a88aa58206dc8c988d644daed4c73e3575ed3d80000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000002a000000000000000000000000000000000000000000000000000000000000003e000000000000000000000000000000000000000000000000000000000000005400000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000000000000474657374000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000000c455845435554455f524f4c450000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c555047524144455f524f4c450000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f574954484452415745525f524f4c4500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000000844414f5f524f4c45000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000844414f5f524f4c45000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000844414f5f524f4c450000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000b4732c813171bdc2dec3e5b499b017ba876d7159000000000000000000000000337e69701a30f149e842a3bb10c376bf36996e990000000000000000000000000000000000000000000000000000000000000001000000000000000000000000fa0d1585e9585c4538e07fcda351290104c102bf0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000fa0d1585e9585c4538e07fcda351290104c102bf0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000246578656375746528616464726573735b5d2c75696e743235365b5d2c62797465735b5d2900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001275706772616465546f28616464726573732900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c455845435554455f524f4c45000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c555047524144455f524f4c45000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000002e759acb781dc9c7277da5749dda5eb79f31871d000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000020000000000000000000000000d7443be718f912214d76705164462e76982e349e0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000b4732c813171bdc2dec3e5b499b017ba876d71590000000000000000000000000000000000000000000000000000000000000020000000000000000000000000e7ebea7c81890b893ec352d1e85fe8055d7d6ab80000000000000000000000000000000000000000000000000000000000000020bdccad0d24572fd7ed2a7577f90615eee25ee2f7b3e9b333695b4c86ae99bf4b0000000000000000000000000000000000000000000000000000000000000003000000000000000000000000a6b71e26c5e0845f74c812102ca7114b6a896ab2000000000000000000000000fa0d1585e9585c4538e07fcda351290104c102bf000000000000000000000000d7443be718f912214d76705164462e76982e349e00000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000002c0000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000002241688f0b9000000000000000000000000d9db270c1b5e3bd161e8c8503c55ceabee7095520000000000000000000000000000000000000000000000000000000000000060d2a14033ccb4a0714114a332edb8b788e259d067bf24da2a10d40505670f134a0000000000000000000000000000000000000000000000000000000000000184b63e800d00000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000025375dbd7057de3b11c896f70b7bd45b136ec55b0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000344a516a5bf000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000d7443be718f912214d76705164462e76982e349e000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001e4a74c3199000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000000010000000000000000000000002d086ed24122cd1fd495590f7370faf1a6fde74e00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001275706772616465546f28616464726573732900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c555047524144455f524f4c45000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000084b658f4620000000000000000000000000000000000000000000000000000000000000040000000000000000000000000337e69701a30f149e842a3bb10c376bf36996e99000000000000000000000000000000000000000000000000000000000000000c455845435554455f524f4c45000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","to":"0x337E69701a30F149e842a3bb10C376bF36996E99","from":"0x25375dBd7057De3B11C896F70B7bd45b136EC55b","gasLimit":{"type":"BigNumber","hex":"0x1a0635"}}, code=ACTION_REJECTED, version=providers/5.7.0)
    at e.value (index.ts:269:28)
    at e.value (index.ts:281:20)
    at json-rpc-provider.ts:259:28 
[]`

**Comment by herbig** [comment]
@tbwebb22 when you jump on front end could you take a look at this bug to start?

**Comment by christopherdancy** [comment]
Hey @herbig I am reviewing this now. Just to clarify - this is for an MVD deployment? If so, I am not sure we even need to support this.

**Comment by herbig** [comment]
@christopherdancy ah yeah you're right, I had assumed it was happening for any deploy, but I just tested the "pure gnosis" and it doesn't occur there.

Whatever the issue is, it isn't present in @mudrila 's deploy path, so yeah don't bother looking into this.

**Comment by christopherdancy** [comment]
Sounds good!
