### ISSUE TITLE
Bug: Toast - TypeError: Cannot read properties of undefined (reading 'content')

### ISSUE THREAD

**Issue by SudoPumpkin** [decent-dao/fractal-interface#547]
Build: content="b7475012e9b161bf205e89a9d2c4439adbd56d9e"

[Localhost](http://localhost:3000/#) displays a console error related to toast reading content. 
The console errors are as follows in all 3 browser types(Chromium, Firefox, Safari):
```
Uncaught TypeError: Cannot read properties of undefined (reading 'content')
    at toToastItem (react-toastify.esm.mjs:168:1)
    at deleteToast (react-toastify.esm.mjs:457:1)
```

_STR_
1. Update to the most recent version of develop
2. Build/rebuild Docker containers
3. Go to http://localhost:3000/# in a browser
4. Open dev tools - console
5. Click the "Create a Fractal" button
6. Observe console error related to toast

![toasterError](https://user-images.githubusercontent.com/86701852/195416319-a53933f4-6847-4b72-bb99-4b05792783c1.gif)

**Comment by Da-Colon** [comment]
Error no longer a problem
