### ISSUE TITLE
wallet address input interpreted as password field for 1password

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#549]
I'm not sure exactly what triggers this from the 1password extension, but ideally we would like to not have this suggest opening 1password.
<img width="1110" alt="Screen Shot 2022-10-12 at 5 14 08 PM" src="https://user-images.githubusercontent.com/384559/195458092-c7b4df4f-957e-4e4f-8f8e-d694448ecff5.png">

**Comment by herbig** [comment]
@Da-Colon in investigating this, I've found the only way to remove this is to set `autocomple="off"` via a `<form>` wrapper.

In thinking more about this, I kind of wonder if we should bake that into the custom input component itself, and just shut off all autocompletes for the app.

In crypto especially, autocompleting on wallet addresses or parameters feels like a security / mistake risk, and we'd rather they always be explicit with intentions.

```
        <form autoComplete="off">
          <Input
            value={trustee.address}
            placeholder={ethers.constants.AddressZero}
            onChange={event => updateAndValidateAddress(event.target.value)}
          />
        </form>
```

**Comment by Da-Colon** [comment]
I will look into this and replicate in the design system. see if I can add it to the theme itself

**Comment by Da-Colon** [comment]
https://1password.community/discussion/94198/autocomplete-off-for-1pass-suggested-fields

> 1Password has historically not respected autocomplete="off" because it's misused by some sites to attempt to prevent users from using password managers.

-.-

**Comment by herbig** [comment]
???

https://1password.community/discussion/comment/590733/#Comment_590733

**Comment by Da-Colon** [comment]
I counter you this one lol https://1password.community/discussion/comment/606453/#Comment_606453

**Comment by Da-Colon** [comment]
So playing around. it appears to pick this input because its the only 'text' input. I've tried to change the typing and it doesn't care along with 'autocomplete="off".

One cheeky solution is to add

```ts
       <Input hidden />
```

with the forms (maybe at the top? i don't know if need to be each page or not haven't tested; that would be annoying) but this removes it
