### ISSUE TITLE
Publish typechain-types and deployment contract addressess to npm

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#588]
From Discord discussion:

"It'd be a nice to have, since this code might not change too much, but since it will go through an audit phase anyway, would just need to republish and update the version in the frontend. it would also reduce some of the hardcoded typechain stuff"

https://discord.com/channels/839548879216181309/958758626003148830/1034141683329290250

**Comment by christopherdancy** [comment]
https://www.npmjs.com/package/@fractal-framework/fractal-contracts
