### ISSUE TITLE
Handle Gnosis API indexing delay

### ISSUE THREAD

**Issue by sethhrbek** [decent-dao/fractal-interface#632]
### Overview

There may be a delay between when a new DAO is created and when Gnosis indexes data for that DAO (and can be served by their API)

The code that fetches data from the Gnosis API should be updated to detect if the DAO address is a Fractal DAO. If the Gnosis API is failing to serve API data for a valid DAO (404 / 500):

1. If a 404 is returned, determine if it's safe to assume this is b/c Gnosis hasn't indexed the data yet, and if so, display a message to the user that their DAO will be ready shortly. 

2. If a 500 is returned, then determine best way to handle this in the UX. 

3. We could also put a small delay (~2 seconds) after DAO creation before redirecting to give extra buffer time.

It may help to also put a refetch (or backoff function) on the API at an interval in either of these cases.

**Comment by herbig** [comment]
From https://github.com/decent-dao/fractal-interface/issues/664

```
Overview

When Creating a Gnosis Safe DAO, the data may not be available yet in the API. We should probably setup some sort of polling to occur for a set amount of time to keep trying, before prompting the user to refresh maybe?
Steps to reproduce

Create Safe (Multisig) DAO -> Deploy DAO.

It should redirect you probably but may get stuck in a loading state.
```

**Comment by Da-Colon** [comment]
I asked that question eariler in chat. I believe the answer was no?
