### ISSUE TITLE
Enable Tally Wallet in web3 modal

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#641]
We just participated in the Tally Ho community call! Let's enable Tally in the app connection modal.

**Comment by adamgall** [comment]
It do already work tho

**Comment by herbig** [comment]
Yeah I think it will appear as "Web 3 Wallet" but there should be a simple option in the modal to enable it appearing with the Tally Logo, like MetaMask does

**Comment by herbig** [comment]
@adamgall actually you're right, we support it, and the logo not appearing is a web3modal bug:

https://github.com/tallycash/extension/issues/1859
