### ISSUE TITLE
Prod (mainnet) release: undo dev redirect

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#653]
@adamgall set up a redirect for the `app.fractalframework.xyz` url to go to `app.dev.fractalframework.xyz`

Steps:
- turned on the "cloudflare proxy" for `app.fractalframework.xyz` (so that requests get routed through cloudflare's servers instead of going directly to netlify)
- created a "redirect rule" in cloudflare called `no-prod-yet`, which redirects all requests from `app.fractalframework.xyz` to `app.dev.fractalframework.zyx`

To undo this:
- delete that "redirect rule" called `no-prod-yet`
- turn off the "cloudflare proxy" for `app.fractalframework.xyz`

Notes:
- i didn't touch netlify or github at all. when `master updates`, the site should still build and deploy, but just won't be accessible because cloudflare gets in the way via that redirect rule 
- the ipfs-hosted `app.fractalframework.xyz` does not redirect, but loads content from the dev build. this will be _reverted_ during the next `master` update, and will go back to loading content from whatever gets built from `master`.

**Comment by adamgall** [comment]
@herbig at your request (https://discord.com/channels/1047935566060212335/1078336474862333962/1084902995130585198), I've removed the redirect rule called `no-prod-yet` and turned off the orange Cloudflare Proxy for `app.fractalframework.xyz`.
