### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#682]
- Updated FAQ page
- DAO creation walkthrough
- Proposal creation walkthrough

- Take out all the old documentation that no longer applies

https://docs.fractalframework.xyz/welcome-to-fractal/

**Comment by herbig** [comment]
@sethhrbek are you still looking at documentation? I think just an FAQ to point the front end links to would probably be the main requirement

**Comment by sethhrbek** [comment]
@herbig -- 
Is there a punch list of front-end links that will need FAQ links? If not, we can sync up to bang this out and then put together the FAQ from the general documentation I am putting together (which should be mostly completed by Thursday).

**Comment by herbig** [comment]
@sethhrbek Tom has an FAQ he's put together that we're working on filling out that could be used in the docs as well:

https://www.notion.so/FAQs-WIP-draft-85614c9c29c545cb8111254c08f5a0bb

**Comment by sethhrbek** [comment]
cool, thanks! I will look through this today.

**Comment by herbig** [comment]
Closing this one, we have some more things to consider for documentation, but the general revamp is good to go, will open further tickets for other improvements.
