### ISSUE TITLE
Explain Allocations on Usul DAO creation / Allocate to Self

### ISSUE THREAD

**Issue by sethhrbek** [decent-dao/fractal-interface#723]
On DAO creation, on the `Token Allocations` section --

We should have some text explaining:
1. What allocation is for
2. That at least one allocation is mandatory to continue

We should also have option to allocate to self quickly (like we do on the delegation modal).

Right now the form also doesn't require an amount to continue (but it should).

**Comment by herbig** [comment]
We've added to the docs some info on delegation.  Closing this, and we'll keep this info in mind as we get user feedback from traction.
