### ISSUE TITLE
Bug: Voting Power not be shown correctly

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#764]
![Image](https://user-images.githubusercontent.com/38386583/206888167-48410aae-c4d4-4b5f-b94b-1f411e7660f7.png)

**Comment by herbig** [comment]
@christopherdancy @tbwebb22 , what's the requirement for creating proposals? You don't need to be a token holder in Usul, right?

**Comment by Da-Colon** [comment]
I figured out what the problem is here. I was able to vot without delegating. @herbig

**Comment by herbig** [comment]
> I figured out what the problem is here. I was able to vote without delegating. @herbig

do you mean `wasn't able` ?

**Comment by herbig** [comment]
@Da-Colon this should be fixed in https://github.com/decent-dao/fractal-interface/pull/824/commits/e0c338f92072df3f22befdee0d6df1ffe34177df
