### ISSUE TITLE
Bug: DAO nav tooltips appear under the nav

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#768]
### Overview

DAO nav tooltips appear under the nav.

This probably occurred with the change @mobiusTripper-crypto and I made in https://github.com/decent-dao/fractal-interface/pull/733/commits/1c17ed7a73de7938327c876599298ac5ccbd01cd

### Steps to reproduce

Hover over left nav DAO options

### Screenshots / Video

<img width="188" alt="Screenshot 2022-12-13 at 1 14 01 PM" src="https://user-images.githubusercontent.com/384559/207418462-55dbb3b1-e847-432b-9c82-f1f31b5ce64f.png">

### Version

Dev (app.dev.fractalframework.xyz/)

### Browser

Firefox

### Operating System

Mac

### web3 wallet

None

**Comment by mobiusTripper-crypto** [comment]
The tooltip is under the GridItem("nav") because of the zIndex="popover". But if you remove that, then the language menu is doesn't display properly when it's displayed over a proposal list. A different solution other than zIndex might need to be found.
