### ISSUE TITLE
Bug: Sorting by newest/oldest doesn't work on Proposals list

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#778]
### Overview

This sorting doesn't seem to do anything.

### Steps to reproduce

Sort by newest/oldest in proposals list, e.g.:

https://app.dev.fractalframework.xyz/#/daos/0xF332aAb56e00f7FDEdEDDC50033Ce5e2D0DD6d61/proposals

Try sorting.

### Screenshots / Video

<img width="1093" alt="Screenshot 2022-12-13 at 8 00 17 PM" src="https://user-images.githubusercontent.com/384559/207478687-1c49b961-2c58-4c52-996a-3ffea2a57473.png">

### Version

Dev (app.dev.fractalframework.xyz/)

### Browser

Firefox

### Operating System

Mac

### web3 wallet

None

**Comment by Da-Colon** [comment]
ah this is because these are by Date not time.

**Comment by Da-Colon** [comment]
@herbig
