### ISSUE TITLE
Bug: Not displaying ENS name for DAOs

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#781]
### Overview

You can search for a DAO based on its ENS name, but we're not displaying it in place of the registered DAO name.

We should display the ENS name in:

DAO Homepage
Nodes page
Favorites list
Treasury

Basically anywhere we could display the name, it should default the ENS if it's available.

### Steps to reproduce

Go to one of the DAOs with an ENS name, e.g. parentmultisig.eth, and observe the name used.

### Screenshots / Video

<img width="1408" alt="Screenshot 2022-12-13 at 8 11 55 PM" src="https://user-images.githubusercontent.com/384559/207480990-8953dd00-1101-4f0f-88f7-f7a43c4d8e83.png">

### Version

Dev (app.dev.fractalframework.xyz/)

### Browser

Firefox

### Operating System

Mac

### web3 wallet

None

**Comment by Da-Colon** [comment]
I don't believe this is a bug on fractal-interface. I believe this is how ENS works? unless you set up the ENS through the account itself (the controller or another thing) then you have to do something else to get this lookup to work

**Comment by herbig** [comment]
> I don't believe this is a bug on fractal-interface. I believe this is how ENS works? unless you set up the ENS through the account itself (the controller or another thing) then you have to do something else to get this lookup to work

Hmm, yeah maybe I don't know how ENS works exactly.

How come I can search for the ENS name and find it, but the ENS name isn't displayed?

**Comment by Da-Colon** [comment]
Let's plan some time to tackle this live, when we get the chance. I'd like to learn more about this and see how you set those ENS names up and see if we can't figure this out.

**Comment by herbig** [comment]
@Da-Colon I just figured out how to properly set the Primary ENS Name (Reverse Record):

1. Register a new ENS name on Georli (ensname.eth)
https://app.ens.domains/

2. Get the ENS NFT id from the transaction on Etherscan:
https://goerli.etherscan.io/tx/0x63c7263c0dcd975231744126c4e7c29b06597fe8df85fd28a5722ccc107775aa

3. Transfer the ENS name from my personal wallet to the DAO via Etherscan, using the transferFrom method (see screenshot)
https://goerli.etherscan.io/address/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85#writeContract

4. Create a proposal to call ENS setName function, with the newly created ENS name (Fractal screenshot).
https://goerli.etherscan.io/address/0xD5610A08E370051a01fdfe4bB3ddf5270af1aA48#writeContract

Target Address: 0xD5610A08E370051a01fdfe4bB3ddf5270af1aA48
Function Name: setName
Function Signature: string name
Parameters: "ensname.eth"

5. Vote for it to pass then execute it.
https://app.dev.fractalframework.xyz/#/daos/0xbFC43fba83971596709cA0f66B1C54B89aad7551/proposals/0xca70c260964e3139b23018b5239d2846295a97d552540b38a77fac6bd1f807b6

https://goerli.etherscan.io/tx/0x949eeacaafa23a13f25729dbf16fcf411f61e3513792d12e53809e6e48b44437

**Comment by herbig** [comment]
Closing this issue, as @Da-Colon is correct, this isn't an issue.

@decent-dao/fractal There is a distinction between having an ENS set to refer to a specific address vs. the _Primary ENS Record_ for that address.

One address can have multiple ENS names resolve to it, but only a single Primary ENS Record, which is what we need to display here.

Also,s earching for an ENS that points to an address but isn't the primary address should still find it, so everything here is working as expected.
