### ISSUE TITLE
Translations not being applied for warning

### ISSUE THREAD

**Issue by mobiusTripper-crypto** [decent-dao/fractal-interface#798]
The warning at appears the very 1st time the user enters the webapp is not translated (this is a toast, so this might be difficult to get done).
![Image](https://user-images.githubusercontent.com/99622829/207735532-2a5be901-5e04-4f9b-ae4e-e7104de820d3.png)

~~When not on a supported chain and selected a language other than english, the chain name is not inserted.~~

**Comment by herbig** [comment]
The second message bug is fixed in https://github.com/decent-dao/fractal-interface/pull/803,

The warning message fix I haven't figured out yet

**Comment by herbig** [comment]
we don't have this warning in the app anymore, so closing this for now
