### ISSUE TITLE
Translate dates and times

### ISSUE THREAD

**Issue by mobiusTripper-crypto** [decent-dao/fractal-interface#799]
Formatted dates and times are not translated to selected language. This is an example on the Create Proposal page.

![Image](https://user-images.githubusercontent.com/99622829/207735959-d83a0b5e-61aa-4400-a6c2-4fa5d8d68ac2.png)

**Comment by herbig** [comment]
Pretty sure this is because my dumb implementation of the dates diff formatting passes in a t function, which doesn't change when the language is changed.

**Comment by herbig** [comment]
scratch that, this is because we're using https://date-fns.org/, formatDistance to calculate times here

to have these translated we'd need to implement a similar function ourself
