### ISSUE TITLE
Bug: Send Assets Modal Bugs

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#822]
### Overview
Cleanup Issues for Send Assets Modal:

1.  Added Toast / Notification. See useTransaction for pattern to follow.
2.  Remove USD switch and all related code.
3. This was something I had to fix in the Treasury assets page as well.

Gnosis's API returns plain Eth in the response, whether it has any or not, so a DAO with zero Eth will display that option in the Send Assets modal.

We should disregard any asset in the Send Assets modal that has a balance of zero, and not display it.

### Steps to reproduce

1. View a DAO that has zero Eth
2. Click Send Assets
3. See that Eth is an option to select

https://app.dev.fractalframework.xyz/#/daos/0xbFC43fba83971596709cA0f66B1C54B89aad7551/treasury

### Screenshots / Video

<img width="609" alt="Screenshot 2022-12-16 at 5 30 52 PM" src="https://user-images.githubusercontent.com/384559/208199911-e4766dff-a677-4f63-bab1-0339337f82ff.png">

### Version

Dev (app.dev.fractalframework.xyz/)

### Browser

Firefox

### Operating System

Mac

### web3 wallet

None

**Comment by herbig** [comment]
@mobiusTripper-crypto is this something you could fix while you're doing the Eth transfer?

**Comment by mobiusTripper-crypto** [comment]
That sounds pretty easy to fix, and if so, i'll bake it into my next Send Assets PR
