### ISSUE TITLE
DIsable Approve button on proposal if user has already approved.

### ISSUE THREAD

**Issue by mobiusTripper-crypto** [decent-dao/fractal-interface#834]
For Multi DAO, if the current connected wallet has already approved a proposal. Disable the Approve button.

![Image](https://user-images.githubusercontent.com/99622829/208512299-10d8ab79-46cb-4a2a-8228-c708f58e9f2b.png)

**Comment by sethhrbek** [comment]
thinking we should hide the "Sign Transaction" + Button if they have already approved.
