### ISSUE TITLE
DAO Creation Input Validation Audit / Improvement

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#846]
### Overview

Most of the DAO creation flow (including subDAO) has very little input validation.

We should go through the whole flow and add common sense validation throughout.

**Comment by Da-Colon** [comment]
Link to Doc (WIP) https://www.notion.so/hulking-cosmos-3e8/Form-Validation-Upgrade-47eefed8f5fa4c98acebc2c8e153d2ce

**Comment by herbig** [comment]
Closing this, as this work is being done by @Da-Colon via https://github.com/decent-dao/fractal-interface/issues/949
