### ISSUE TITLE
Error in e2e-tests.yml

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#866]
So creating this issue to track. Looks like there is an ongoing discussion of the issue here. https://github.com/cschleiden/vscode-github-actions/issues/101

it appears to work fine. but what I'm gathering from the discussion is that the syntax for YML doesn't quite support secrets appearing in `run` commands. Doesn't seem to affect anything currently. but should follow up on this when the fix is figured out

![image](https://user-images.githubusercontent.com/38386583/210249233-27428da2-a422-443f-abea-c1fa059820e8.png)

**Comment by herbig** [comment]
@Da-Colon is this still an issue?

**Comment by Da-Colon** [comment]
I'll put this on my radar and look into again and see if there is a fix yet.

**Comment by herbig** [comment]
This was marked as fixed and I'm no longer seeing an error in VS code

https://github.com/cschleiden/vscode-github-actions/issues/101#issuecomment-1479872748
