### ISSUE TITLE
DAO Heirarchy - Freeze Issues

### ISSUE THREAD

**Issue by sethhrbek** [decent-dao/fractal-interface#871]
Steps to recreate:

Setup
1. Create a multisig RootDAO, adding yourself as a signer.
2. Create a multisig SubDAO of this RootDAO. Add yourself as a signer to this DAO as well. Use default params for all parent controls.

Parent DAO Freeze:
1. Visit ParentDAO Heirarchy page.
2. See that the Child DAO cannot be frozen (not an option in the menu).

![Image](https://user-images.githubusercontent.com/43755993/210420627-bc8a384e-0e6c-4911-bc63-00c07a53baaf.png)

SubDAO Freeze
1. Visit SubDAO Heirarchy page.
2. See that it allows you to freeze both the Parent *and* Child DAOs. The parent should not be freezable.

![Image](https://user-images.githubusercontent.com/43755993/210420534-657700bb-2ed4-4659-b1d2-3a5fac81d296.png)

**Comment by Da-Colon** [comment]
`src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx`

There is a conditional here to set the freezeOption:

```ts
if (
      freezeData &&
      !isWithinFreezeProposalPeriod(freezeData, currentTime) &&
      !isWithinFreezePeriod(freezeData, currentTime) &&
      freezeData.userHasVotes
    ) {
      const freezeOption = {
        optionKey: 'optionInitiateFreeze',
        onClick: () => guardContracts.vetoVotingContract?.castFreezeVote(),
      };
      return [createSubDAOOption, freezeOption];
    } else {
      return [createSubDAOOption];
    }
```
