### ISSUE TITLE
Explain parent signer when creating a SubDAO.

### ISSUE THREAD

**Issue by sethhrbek** [decent-dao/fractal-interface#872]
**Needs discussion**

Need to add some text explaining that the parent will be added as a signer when creating a multi sig subDAO.

right now if you create a subDAO, the subDAO will show as having 1 more signer then it actually does.

OR

Subtract 1 from signers total on multisig subDAOs (this is kind of a bad representation hack)

**Comment by herbig** [comment]
Closing this, as this is being addressed in https://github.com/decent-dao/fractal-interface/issues/886
