### ISSUE TITLE
Make Proposals Menu item active when viewing proposal

### ISSUE THREAD

**Issue by sethhrbek** [decent-dao/fractal-interface#873]
When viewing an individual proposal, make the proposal menu item active (yellow).

**Comment by herbig** [comment]
Oh nice catch

**Comment by sethhrbek** [comment]
@mudrila -- I think we should also add the name of the DAO on this page. The DAO name is shown on all the other main DAO pages, but doesn't appear on this page.

**Comment by herbig** [comment]
@mudrila yeah just go for it!
