### ISSUE TITLE
Handle Decoded TX failure

### ISSUE THREAD

**Issue by sethhrbek** [decent-dao/fractal-interface#876]
If Gnosis is unable to decode transactions, we should show the user a message. 

Recommend keeping the "Show executable code" dropdown, but in the dropdown show a message of "Unable to decode proposal transaction data".

To test this, create a proposal with a junk transaction (call some function that doesn't exist on an random address).

Gnosis shouldn't be able to decode this TX.

**Comment by herbig** [comment]
I think keeping it simple with the message you suggested works great for this.
