### ISSUE TITLE
Add "Copy Treasury Address" on Treasury Page

### ISSUE THREAD

**Issue by sethhrbek** [decent-dao/fractal-interface#879]
On treasury page, it would be nice if you could quickly copy the treasury address to send assets to it.

**Comment by herbig** [comment]
Pending design feedback https://discord.com/channels/839548879216181309/958758626003148830/1060970111265144892

**Comment by herbig** [comment]
We have design for this already

**Comment by herbig** [comment]
Figma designs ready for this

![image](https://user-images.githubusercontent.com/384559/224131142-6d939c64-e84d-4fcc-94a8-0881ef5f3ff7.png)
