### ISSUE TITLE
Fractal Themed 404 Page

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#892]
### Overview

We should create a proper 404 page.

<img width="1470" alt="Screenshot 2023-01-06 at 11 38 23 AM" src="https://user-images.githubusercontent.com/384559/211056726-80e9f3a0-9d26-41f7-8ac4-4adcfc30e8f9.png">

**Comment by xraystyle1980** [comment]
3 versions for review: 
1. No wallet connected, no back button
2. Wallet connected with back button
3. Wallet connected, back button disabled

These design are already in the main Figma file and ready to go (skipped the branching this time as these are super basic)
Of course let me know if we need to tweak and we can do it. 

<img width="1250" alt="CleanShot 2023-02-15 at 12 06 37@2x" src="https://user-images.githubusercontent.com/18615633/219101227-7a6008a7-ee03-4613-a7ef-7a4473025352.png">

In Figma:
https://www.figma.com/file/cO1nBoNZCmMKCwCCpyTxfx/%F0%9F%A6%84-Fractal-%7C-Pages-%26-Flows-Master?node-id=5258%3A30574&t=UXm6BwdZSZJVkcY2-4

**Comment by herbig** [comment]
Awesome, this looks sick.

Moving this ticket to "On Deck" and we can prioritize when to build this out.
