### ISSUE TITLE
Bug: Phantom proposal on proposal list load

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#909]
### Overview

> When doing a hard reload on this page, a “phantom proposal” record appears for a second or two which is then replaced with the correct data (either the empty message, or actual proposals). The “phantom proposal” seems to include DAO-specific and somewhat relevant data which is interesting to me.

> #0xc20b...9882 Proposal to execute 7 transactions 7 addresses that will Send 60,000,000 DCNT To 0x0000...0000

### Steps to reproduce

n/a

### Version

Dev (app.dev.fractalframework.xyz/)

### Browser

Chrome (or Chromium based)

### Operating System

None

### web3 wallet

None

**Comment by herbig** [comment]
This is feedback from Adam.  @mudrila is this the module transaction from when the DAO was created? Any idea what's going on with this?

**Comment by adamgall** [comment]
@mudrila 
this is with the original DAO address that I used when making my initial report: `0xb6b5dEE6427dC1FE63E78B44661f21B542Fa8F3C`

https://user-images.githubusercontent.com/706929/214857143-a580fbc7-82b7-43fe-b2ad-5d6566964bd6.mov

**Comment by herbig** [comment]
I can't reproduce this, so likely a refactor fixed this one @mudrila 

Closing this.
