### ISSUE TITLE
Bug: new proposal requires refresh

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#910]
### Overview

> After creating a new proposal, it doesn’t show up on the Proposals page unless a page refresh happens.

### Steps to reproduce

n/a

### Version

Dev (app.dev.fractalframework.xyz/)

### Browser

Chrome (or Chromium based)

### Operating System

None

### web3 wallet

None

**Comment by tbwebb22** [comment]
I'll be tackling this one. Looks like this is only an issue for Multisig DAOs. On a Usul DAO, proposals page seems to get updated automatically with the new proposal
