### ISSUE TITLE
Bug: Make Etherscan links generic to the network

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#918]
### Overview

All of our Etherscan links point to Eth mainnet currently, even on Georli.

In order to deploy to any network other than test or mainnet, we'll need to make these links generic to the specific network.

**Comment by Da-Colon** [comment]
Update: The etherscan links now will handle etherscan testnets (Goerli, etc). We will need do some refactoring a little once we support networks that have different domains from etherscan ie [polyscan](https://polygonscan.com/)

**Comment by herbig** [comment]
@Da-Colon is this something you're working on for the Polygon support?

**Comment by Da-Colon** [comment]
Not for the current PR, but one of the spin offs for sure. I think we can just add exploreURL to the network config files and use that to pick the domain rather current setup.
