### ISSUE TITLE
Bug: Scrollbars in Proposal creation

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#939]
### Overview

This appears to be only on Chrome. See screenshots.

Depending on the fix, please also investigate other inputs in the app (DAO creation) to ensure they do not appear there as well.

### Steps to reproduce

View Proposal Creation on Chrome.

### Screenshots / Video

![image](https://user-images.githubusercontent.com/384559/214602918-ca35d18b-8f5b-4271-98f1-21ba7ac516d8.png)

![214423084-890c44f9-b567-4036-acb5-282df92f0d3e](https://user-images.githubusercontent.com/384559/214602943-599eaa93-2c10-436c-a424-fbd02df58416.png)

### Version

Dev (app.dev.fractalframework.xyz/)

### Browser

Chrome (or Chromium based)

### Operating System

None

### web3 wallet

None

**Comment by Da-Colon** [comment]
This might be due to the theming. 

when changing the `size` property to `xl` rather than 'base' the scrollbars disappear.

**Comment by Da-Colon** [comment]
Question: @herbig I think the move here is just changing these into normal inputs? looking at the code I'm not sure why not? As far as the scrollbar goes. I believe the fix here is removing the `base` size from Textarea input. when the Text area is below a certain height it appears.
