### ISSUE TITLE
Update frontend for new Usul contract

### ISSUE THREAD

**Issue by tbwebb22** [decent-dao/fractal-interface#952]
### Overview

The frontend needs to be updated to support the new modified Usul contract. 
Changes affecting the frontend include:

**LinearTokenVoting**
- `OZLinearVoting` contract renamed to `LinearTokenVoting` 
- `receiveStrategy` function renamed to `timelockProposal`
- New `isProposer` function that returns whether an address can submit a proposal. This probably won't need to be implemented on the FE yet since this implementation always returns True
- `getProposal` function added for getting proposal details
- `calculateWeight` renamed to `getVotingWeight`
- `quorumDenominator` constant updated from 100 to 1,000,000

**FractalUsul**
- `submitProposalWithMetadata` function renamed to `submitProposal`
- `submitProposal` interface changed to:
    `function submitProposal(
        address strategy,
        bytes memory data,
        FractalUsul.Transaction[] calldata transactions,
        string calldata metadata
    ) external;`
- `ProposalCreated` event changed to: 
`    event ProposalCreated(
        address strategy,
        uint256 proposalId,
        address proposer,
        Transaction[] transactions,
        string metadata
    );`
- This function now emits a single event, called `ProposalCreated`. This event had a duplicate of proposald / proposalNumber, so this duplicate was also removed. This event now includes the following fields:
`    event ProposalCreated(
        address strategy,
        uint256 proposalId,
        address proposer,
        Transaction[] transactions,
        string title,
        string description, 
        string documentationUrl
    );`
- `Executing` state renamed to `Executable`
- `StrategyFinalized` event renamed to `ProposalTimelocked`
- `receiveStrategy` function renamed to `timelockProposal`
- Proposal states `Uninitialized` and `Cancelled` removed
- `state` function renamed to `proposalState` for getting the state of a proposal
- ProposalState Enum updated to: 
    `enum ProposalState {
        ACTIVE,
        TIMELOCKED,
        EXECUTABLE,
        EXECUTED
    }`

**UsulVetoGuard & VetoGuard**
- `queueProposal` function renamed to `timelockProposal`
- `ProposalQueued` event renamed to `ProposalTimelocked`

**Comment by herbig** [comment]
@Da-Colon @tbwebb22 @mudrila @sethhrbek 

The Usul updates are going to invalidate all of our current DAOs on the frontend, right?

Is there a way to support them and support migrating to the new contracts, or is that too much lift currently with everything else we're working on?

**Comment by herbig** [comment]
@tbwebb22 it might be good to update this ticket with further thoughts.

There was a method @mudrila pointed out that you refactored to return rather than revert, though I can't recall what that was?

**Comment by tbwebb22** [comment]
Yeah so these contract updates will definitely invalidate the existing DAOs. I was planning on getting this issue updated at the end of this PR, since there are still a bunch of changes coming.

That function you're thinking of is the `isPassed` function on the `LinearTokenVoting` contract

**Comment by herbig** [comment]
yeah, definitely expecting that this will invalidate DAOs..

given that I'm now rethinking supporting Polygon for this event

**Comment by herbig** [comment]
@decent-dao/fractal not related to contract changes, but since we'll be making breaking changes, we might want to discuss changing the `/nodes` path for hierarchy, because we moved away from the term 'nodes' in the UI but that's still the path.
