### ISSUE TITLE
Release workflows

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-interface#969]
from @Da-Colon:

- Dockerize Playwright
- Cache Docker builds in Github action (I think this is a possible)
- Deploy Preview and Dev and Prod deployments happen through Github Actions versus automatically via Netlify
  - This will allow us to run tests before deployment
- Deploy Preview should deploy on new PR created/updated
- Dev and Prod deployments should happen through tag releases? (maybe just prod)

**Comment by Da-Colon** [comment]
Started a here. 

https://www.notion.so/hulking-cosmos-3e8/Fractal-DevOps-96d862cb0e1d4f51b179d9d630066aa4?pvs=4

**Comment by herbig** [comment]
@Da-Colon testing testing

**Comment by herbig** [comment]
@Da-Colon test!

**Comment by herbig** [comment]
@Da-Colon test!

**Comment by herbig** [comment]
@Da-Colon test!

**Comment by herbig** [comment]
@Da-Colon this one has to work 🤞

**Comment by herbig** [comment]
we should be able to tag multiples, like @mudrila and @sethhrbek

**Comment by herbig** [comment]
how about now @mudrila and @sethhrbek ?

**Comment by herbig** [comment]
how about NOW @mudrila and @sethhrbek ?

**Comment by herbig** [comment]
what if I tag @decent-dao/fractal

**Comment by herbig** [comment]
58th time's a charm...

@Da-Colon  HELLO
@decent-dao/fractal  hello also!

**Comment by herbig** [comment]
58th time's a charm...

@Da-Colon HELLO
https://github.com/orgs/decent-dao/teams/fractal hello also!

**Comment by Da-Colon** [comment]
Currently we are sticking with Netlify handling CI/CD. We have run into some issues regarding building deploying the lastest version of NextJS. It appears that for now that NextJS must be built using Netlify NextJS Runtime or else it doesn't properly host the site.

**Comment by adamgall** [comment]
Closing this because it's not important right now.
