### ISSUE TITLE
Refactor/fix Usul subDAO veto guard handling

### ISSUE THREAD

**Issue by mudrila** [decent-dao/fractal-interface#976]
After implementing  https://github.com/decent-dao/fractal-interface/pull/971 - we discovered that there're certain cases in code, where we're ignoring `vetoGuard` for Usul-based subDAOs.

So, something like following code in `useActivities` - should be fixed and proper veto guard should be passed.

```
vetoGuardType === VetoGuardType.MULTISIG
      ? (vetoGuardContract?.asSigner as VetoGuard)
      : undefined
```

**Comment by sethhrbek** [comment]
This makes sense to focus on -- I'm assuming some Usul functionality is broken due to this issue, which would make it a solid priority.

**Comment by herbig** [comment]
> I feel like we should hold this issue until we're done with Azorius adoption on Front-End side

yeah good call

**Comment by Da-Colon** [comment]
This should be taken care of as well
